package restaurante.sakura;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class TelaProdutos extends javax.swing.JFrame {

    private javax.swing.table.DefaultTableModel modelo;
    private ProdutoDAO produtoDAO;

   public TelaProdutos() {
    initComponents();

    modelo = (javax.swing.table.DefaultTableModel) tblProdutos.getModel();

    modelo.setColumnIdentifiers(new Object[]{
        "ID", "Produto", "Categoria", "Preço", "Disponível"
    });

    produtoDAO = new ProdutoDAO();
    carregarProdutos();

    tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = tblProdutos.getSelectedRow();

            if (linha >= 0) {
                txtId.setText(tblProdutos.getValueAt(linha, 0).toString());
                txtNome.setText(tblProdutos.getValueAt(linha, 1).toString());
                txtCategoria.setText(tblProdutos.getValueAt(linha, 2).toString());
                txtPreco.setText(tblProdutos.getValueAt(linha, 3).toString());
                cbDisponivel.setSelectedItem(
                    tblProdutos.getValueAt(linha, 4).toString()
                );
            }
        }
    });
}

private void carregarProdutos() {

    try {
        modelo.setRowCount(0);

        for (Produto produto : produtoDAO.listar()) {

            modelo.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getCategoria(),
                produto.getPreco(),
                produto.isDisponivel() ? "Sim" : "Não"
            });
        }

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Erro ao carregar produtos:\n" + e.getMessage()
        );
    }

    tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = tblProdutos.getSelectedRow();

            if (linha >= 0) {
                txtId.setText(tblProdutos.getValueAt(linha, 0).toString());
                txtNome.setText(tblProdutos.getValueAt(linha, 1).toString());
                txtCategoria.setText(tblProdutos.getValueAt(linha, 2).toString());
                txtPreco.setText(tblProdutos.getValueAt(linha, 3).toString());
                cbDisponivel.setSelectedItem(
                    tblProdutos.getValueAt(linha, 4).toString()
                );
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblDisponivel = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        cbDisponivel = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("Id");

        lblProduto.setText("Produto");

        lblCategoria.setText("Categoria");

        lblPreco.setText("Preço");

        lblDisponivel.setText("Disponível");

        cbDisponivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Produto", "Categoria", "Preço", "Disponivel"
            }
        ));
        jScrollPane4.setViewportView(tblProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto)
                            .addComponent(lblCategoria)
                            .addComponent(lblPreco)
                            .addComponent(lblDisponivel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(txtNome)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnLimpar)))
                                .addGap(50, 50, 50)
                                .addComponent(btnAlterar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(cbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(510, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(txtCategoria))
                                .addGap(50, 50, 50)
                                .addComponent(btnCadastrar)
                                .addGap(362, 362, 362))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExcluir)
                        .addGap(156, 156, 156)
                        .addComponent(btnVoltar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAlterar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisponivel)
                    .addComponent(cbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
try {

    int id = Integer.parseInt(txtId.getText());
    String nome = txtNome.getText();
    String categoria = txtCategoria.getText();
    double preco = Double.parseDouble(txtPreco.getText());

    boolean disponivel =
            cbDisponivel.getSelectedItem().toString().equals("Sim");

    if (nome.isEmpty() || categoria.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos."
        );
        return;
    }

    Produto produto = new Produto(
        id,
        nome,
        categoria,
        preco,
        disponivel
    );

    produtoDAO.cadastrar(produto);

    JOptionPane.showMessageDialog(
        this,
        "Produto cadastrado com sucesso!"
    );

    carregarProdutos();

    txtId.setText("");
    txtNome.setText("");
    txtCategoria.setText("");
    txtPreco.setText("");
    cbDisponivel.setSelectedIndex(0);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
        this,
        "ID e preço devem ser números."
    );

} catch (java.sql.SQLException e) {

    JOptionPane.showMessageDialog(
        this,
        "Erro ao cadastrar produto:\n" + e.getMessage()
    );
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
try {

    int id = Integer.parseInt(txtId.getText());
    String nome = txtNome.getText();
    String categoria = txtCategoria.getText();
    double preco = Double.parseDouble(txtPreco.getText());

    boolean disponivel =
            cbDisponivel.getSelectedItem().toString().equals("Sim");

    if (nome.isEmpty() || categoria.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos."
        );
        return;
    }

    Produto produto = new Produto(
        id,
        nome,
        categoria,
        preco,
        disponivel
    );

    produtoDAO.alterar(produto);

    JOptionPane.showMessageDialog(
        this,
        "Produto alterado com sucesso!"
    );

    carregarProdutos();

    txtId.setText("");
    txtNome.setText("");
    txtCategoria.setText("");
    txtPreco.setText("");
    cbDisponivel.setSelectedIndex(0);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
        this,
        "ID e preço devem ser números."
    );

} catch (java.sql.SQLException e) {

    JOptionPane.showMessageDialog(
        this,
        "Erro ao alterar produto:\n" + e.getMessage()
    );
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
int linha = tblProdutos.getSelectedRow();

if (linha < 0) {
    JOptionPane.showMessageDialog(
        this,
        "Selecione um produto na tabela."
    );
    return;
}

int resposta = JOptionPane.showConfirmDialog(
    this,
    "Deseja realmente excluir este produto?",
    "Confirmar exclusão",
    JOptionPane.YES_NO_OPTION
);

if (resposta == JOptionPane.YES_OPTION) {

    try {

        int id = Integer.parseInt(
            tblProdutos.getValueAt(linha, 0).toString()
        );

        produtoDAO.excluir(id);

        JOptionPane.showMessageDialog(
            this,
            "Produto excluído com sucesso!"
        );

        carregarProdutos();

        txtId.setText("");
        txtNome.setText("");
        txtCategoria.setText("");
        txtPreco.setText("");
        cbDisponivel.setSelectedIndex(0);

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Erro ao excluir produto:\n" + e.getMessage()
        );
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
txtId.setText("");
txtNome.setText("");
txtCategoria.setText("");
txtPreco.setText("");
cbDisponivel.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaProdutos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbDisponivel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDisponivel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
