/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.sakura;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */

    /**
     * Creates new form TelaPedidos
     */
    public class TelaPedidos extends javax.swing.JFrame {

    private double total = 0;

    private ClienteDAO clienteDAO;
    private ProdutoDAO produtoDAO;
    private PedidoDAO pedidoDAO;

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName());

    public TelaPedidos() {
        initComponents();

        clienteDAO = new ClienteDAO();
        produtoDAO = new ProdutoDAO();
        pedidoDAO = new PedidoDAO();

        carregarClientes();
        carregarProdutos();
    }

    private void carregarClientes() {

        try {

            cbCliente.removeAllItems();

            for (Cliente cliente : clienteDAO.listar()) {

                cbCliente.addItem(
                    cliente.getId() + " - " + cliente.getNome()
                );
            }

        } catch (java.sql.SQLException e) {

            JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar clientes:\n" + e.getMessage()
            );
        }
    }

    private void carregarProdutos() {

        try {

            cbProduto.removeAllItems();

            for (Produto produto : produtoDAO.listar()) {

                if (produto.isDisponivel()) {

                    cbProduto.addItem(
                        produto.getId() + " - " + produto.getNome()
                    );
                }
            }

        } catch (java.sql.SQLException e) {

            JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar produtos:\n" + e.getMessage()
            );
        }
    }

    /**
     * This method is called from within the constructor...

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        lblProduto = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        Jscrollpane = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCliente.setText("Cliente");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joao", "Maria", "Carlos" }));
        cbCliente.addActionListener(this::cbClienteActionPerformed);

        lblProduto.setText("Produto");

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sushi", "Temaki", "Yakisoba" }));

        lblQuantidade.setText("Quantidade");

        btnAdicionar.setText("Adicionar Item");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(this::btnFinalizarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço", "Subtotal"
            }
        ));
        Jscrollpane.setViewportView(tblItens);

        lblTotal.setText("Total: 0,00R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuantidade)
                        .addGap(42, 42, 42)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addGap(382, 382, 382))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Jscrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnCancelar)
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProduto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnAdicionar)))
                .addGap(415, 445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnFinalizar)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade))
                        .addGap(66, 66, 66)))
                .addComponent(Jscrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         javax.swing.table.DefaultTableModel tabela =
            (javax.swing.table.DefaultTableModel) tblItens.getModel();

    tabela.setRowCount(0);

    total = 0;

    lblTotal.setText("Total: R$ 0,00");

    txtQuantidade.setText("");

    JOptionPane.showMessageDialog(
        this,
        "Pedido cancelado."
    );
  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

    if (tblItens.getRowCount() == 0) {

        JOptionPane.showMessageDialog(
            this,
            "Adicione pelo menos um item ao pedido."
        );

        return;
    }

    try {

        // Pega o ID do cliente selecionado
        String clienteSelecionado =
                cbCliente.getSelectedItem().toString();

        int clienteId = Integer.parseInt(
            clienteSelecionado.split(" - ")[0]
        );

        // Salva o pedido e recebe o ID gerado pelo banco
        int pedidoId = pedidoDAO.cadastrarPedido(
            clienteId,
            total
        );

        // Percorre os itens da tabela
        for (int i = 0; i < tblItens.getRowCount(); i++) {

            String nomeProduto =
                    tblItens.getValueAt(i, 0).toString();

            int quantidade =
                    Integer.parseInt(
                        tblItens.getValueAt(i, 1).toString()
                    );

            String precoTexto =
                    tblItens.getValueAt(i, 2).toString()
                    .replace("R$", "")
                    .replace(",", ".")
                    .trim();

            String subtotalTexto =
                    tblItens.getValueAt(i, 3).toString()
                    .replace("R$", "")
                    .replace(",", ".")
                    .trim();

            double preco = Double.parseDouble(precoTexto);
            double subtotal = Double.parseDouble(subtotalTexto);

            // Encontra o produto pelo nome
            Produto produtoEncontrado = null;

            for (Produto produto : produtoDAO.listar()) {

                if (produto.getNome().equals(nomeProduto)) {
                    produtoEncontrado = produto;
                    break;
                }
            }

            if (produtoEncontrado != null) {

                pedidoDAO.cadastrarItem(
                    pedidoId,
                    produtoEncontrado.getId(),
                    quantidade,
                    preco,
                    subtotal
                );
            }
        }

        JOptionPane.showMessageDialog(
            this,
            "Pedido finalizado e salvo no banco!\n"
            + "Número do pedido: " + pedidoId + "\n"
            + String.format("Total: R$ %.2f", total)
        );

        // Limpa a tela depois de salvar
        javax.swing.table.DefaultTableModel tabela =
                (javax.swing.table.DefaultTableModel)
                tblItens.getModel();

        tabela.setRowCount(0);

        total = 0;

        lblTotal.setText("Total: R$ 0,00");

        txtQuantidade.setText("");

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Erro ao salvar pedido:\n" + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

    String produtoSelecionado =
            cbProduto.getSelectedItem().toString();

    int quantidade;

    try {

        quantidade = Integer.parseInt(
            txtQuantidade.getText()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Digite uma quantidade válida."
        );

        return;
    }

    if (quantidade <= 0) {

        JOptionPane.showMessageDialog(
            this,
            "A quantidade deve ser maior que zero."
        );

        return;
    }

    try {

        // Pega o ID antes do " - "
        int produtoId = Integer.parseInt(
            produtoSelecionado.split(" - ")[0]
        );

        // Busca o produto e o preço no banco
        Produto produto = produtoDAO.buscarPorId(produtoId);

        if (produto == null) {

            JOptionPane.showMessageDialog(
                this,
                "Produto não encontrado."
            );

            return;
        }

        double preco = produto.getPreco();

        double subtotal = preco * quantidade;

        javax.swing.table.DefaultTableModel tabela =
                (javax.swing.table.DefaultTableModel)
                tblItens.getModel();

        tabela.addRow(new Object[]{
            produto.getNome(),
            quantidade,
            String.format("R$ %.2f", preco),
            String.format("R$ %.2f", subtotal)
        });

        total += subtotal;

        lblTotal.setText(
            String.format("Total: R$ %.2f", total)
        );

        txtQuantidade.setText("");

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Erro ao buscar produto:\n" + e.getMessage()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClienteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Jscrollpane;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
